data:
    preprocessing:
        resize: [240, 320]

model:
    name: 'UltraPoint'
    pretrained: null #'../assets/logs/ultrapoint_2025-05-22_11:04:17/checkpoints/UltraPoint_77000_checkpoint.pth.tar'
    detection_threshold: 0.015
    nms_radius: 4
    max_num_keypoints: 1024
    remove_borders: 8
    top_k: 1024
    batch_size: 1
    eval_batch_size: 1

seed: 0
precision: medium
logging:
  level: DEBUG
  directory: ../assets/logs/benchmarks
