data:
  add_augmentation_to_test_set: false # set to true to evaluate with noise
  augmentation:
    homographic:
      enable: true
      enable_train: true
      enable_val: false
      params:
        allow_artifacts: true
        max_angle: 1.57
        patch_ratio: 0.8
        perspective: true
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        rotation: true
        scaling: true
        scaling_amplitude: 0.2
        translation: true
        translation_overflow: 0.05
      valid_border_margin: 2
    photometric:
      enable: true
      enable_train: true
      enable_val: false
      params:
        additive_gaussian_noise:
          stddev_range:
          - 0
          - 15
        additive_shade:
          kernel_size_range:
          - 50
          - 100
          transparency_range:
          - -0.5
          - 0.8
        additive_speckle_noise:
          prob_range:
          - 0
          - 0.0035
        motion_blur:
          max_kernel_size: 7
        random_brightness:
          max_abs_change: 75
        random_contrast:
          strength_range:
          - 0.3
          - 1.8
      random_order: true
  cache_in_memory: true
  dataset: SyntheticDatasetGaussian
  gaussian_label:
    enable: false
    params:
      GaussianBlur:
        sigma: 0.2
  generation:
    image_size:
    - 960
    - 1280
    params:
      draw_multiple_polygons:
        kernel_boundaries: (50, 100)
      draw_stripes:
        transform_params: (0.1, 0.1)
      generate_background:
        max_kernel_size: 500
        max_rad_ratio: 0.031
        min_kernel_size: 150
        min_rad_ratio: 0.02
    random_seed: 0
    split_sizes:
      test: 500
      training: 10000
      validation: 200
  num_parallel_calls: 10
  on-the-fly: false
  path: ../assets/datasets/
  preprocessing:
    blur_size: 21
    resize:
    - 120
    - 160
  primitives: all
  suffix: v6
  test_size: -1
  test_workers: 16
  train_workers: 16
  truncate:
    draw_ellipses: 0.3
    draw_stripes: 0.2
    gaussian_noise: 0.1
  validation_size: -1
  warped_pair:
    enable: false  # false when training only on detector
    params:
      allow_artifacts: true
      max_angle: 1.57
      patch_ratio: 0.85
      perspective: true
      perspective_amplitude_x: 0.2
      perspective_amplitude_y: 0.2
      rotation: true
      scaling: true
      scaling_amplitude: 0.2
      translation: true
    valid_border_margin: 3
logging:
  directory: ../assets/logs
  level: DEBUG
model:
  batch_size: 64
  dense_loss:
    enable: false
    params:
      descriptor_dist: 4
      lambda_d: 800
  detection_threshold: 0.001
  detector_loss:
    loss_type: softmax
  eval_batch_size: 16
  kernel_reg: 0.0
  lambda_loss: 0
  learning_rate: 0.001
  name: SuperPointNet
  nms: 4
  other_settings: train 2d, gauss 0.5
  params: {}
  sparse_loss:
    enable: true
    params:
      dist: cos
      lamda_d: 1
      method: 2d
      num_masked_non_matches_per_match: 100
      num_matching_attempts: 1000
  subpixel:
    enable: false
precision: medium
reset_iter: true
retrain: true
save_interval: 2000
seed: 0
tensorboard_interval: 1000
train_iter: 200000
train_show_interval: 1000
trainer: TrainModelHeatmap
validation_interval: 1000
validation_size: 10
