data:
    augmentation:
        homographic:
            enable: false
            valid_border_margin: 0
        photometric:
            enable: true
            params:
                additive_gaussian_noise:
                    stddev_range:
                    - 0
                    - 10
                additive_shade:
                    kernel_size_range:
                    - 100
                    - 150
                    transparency_range:
                    - -0.5
                    - 0.5
                additive_speckle_noise:
                    prob_range:
                    - 0
                    - 0.0035
                motion_blur:
                    max_kernel_size: 3
                random_brightness:
                    max_abs_change: 50
                random_contrast:
                    strength_range:
                    - 0.5
                    - 1.5
            primitives: all
            random_order: true
    cache_in_memory: false
    dataset: Coco
    gaussian_label:
        enable: true
        params:
            GaussianBlur:
                sigma: 0.2
    homography_adaptation:
        enable: false
    labels: ../assets/datasets/coco/train2014/pseudo_labels
    num_parallel_calls: 10
    path: ../assets/datasets/coco/train2014
    preprocessing:
        resize:
        - 240
        - 320
    test_workers: 16
    train_workers: 16
    truncate: null
    validation_size: 100
    warped_pair:
        enable: true
        params:
            allow_artifacts: true
            max_angle: 1.57
            patch_ratio: 0.85
            perspective: true
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            rotation: true
            scaling: true
            scaling_amplitude: 0.2
            translation: true
        valid_border_margin: 3
logging:
    directory: ../assets/logs
    level: DEBUG
model:
    batch_size: 8
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4
            lambda_d: 800
    detection_threshold: 0.015
    detector_loss:
        enable: true
        loss_type: softmax
    eval_batch_size: 8
    lambda_loss: 1
    learning_rate: 0.0001
    name: SuperPointNet
    nms: 4
    nn_thresh: 0.7
    other_settings: train 2d, gauss 0.2
    params: {}
    sparse_loss:
        enable: true
        params:
            dist: cos
            lamda_d: 1
            method: 2d
            num_masked_non_matches_per_match: 100
            num_matching_attempts: 1000
    subpixel:
        enable: false
        loss_func: subpixel_loss_no_argmax
        params:
            subpixel_channel: 2
        settings: predict flow directly
precision: medium
pretrained: null
reset_iter: true
save_interval: 2000
seed: 0
tensorboard_interval: 200
train_iter: 200000
trainer: TrainerHeatmap
validation_interval: 2000
validation_size: 5
