data:
    dataset: 'Coco'
    path: '../assets/datasets/coco/train2014'
    labels: '../assets/datasets/coco/train2014/pseudo_labels'
    cache_in_memory: false
    truncate: null
    num_parallel_calls: 10
    validation_size: 100
    preprocessing:
        resize: [240, 320]
    gaussian_label:
        enable: true
        params:
            GaussianBlur: {sigma: 0.2}
    homography_adaptation:
        enable: false
    augmentation:
        photometric:
            enable: true
            primitives: "all"
            random_order: true
            params:
                random_brightness: {max_abs_change: 50}
                random_contrast: {strength_range: [0.5, 1.5]}
                additive_gaussian_noise: {stddev_range: [0, 10]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.5]
                    kernel_size_range: [100, 150]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: false
            valid_border_margin: 0
    warped_pair:
        enable: true
        params:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.2
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            patch_ratio: 0.85
            max_angle: 1.57
            allow_artifacts: true
        valid_border_margin: 3
    workers: 8

model:
    name: 'SuperPointNet'
    params: {
    }
    detector_loss:
        enable: true
        loss_type: 'softmax'
    batch_size: 8
    eval_batch_size: 8
    learning_rate: 0.0001
    detection_threshold: 0.015
    lambda_loss: 1
    nms: 4
    nn_thresh: 0.7
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4
            lambda_d: 800
    sparse_loss:
        enable: true
        params:
            num_matching_attempts: 1000
            num_masked_non_matches_per_match: 100
            lamda_d: 1
            dist: 'cos'
            method: '2d'
    other_settings: 'train 2d, gauss 0.2'
    subpixel:
        enable: false
        params:
            subpixel_channel: 2
        settings: 'predict flow directly'
        loss_func: 'subpixel_loss_no_argmax' # subpixel_loss, subpixel_loss_no_argmax

trainer: 'TrainModelHeatmap'
pretrained: null
retrain: true
reset_iter: true
train_iter: 200000
validation_interval: 200
tensorboard_interval: 200
save_interval: 200
validation_size: 5

seed: 0
precision: medium
logging:
  level: DEBUG
  directory: ../assets/logs
