data:
    train_labels_folder: '../../../datasets/navigation/ss/ir/train/pseudo_labels'
    train_images_folder: '../../../datasets/navigation/ss/ir/train/all'
    val_labels_folder: '../../../datasets/navigation/ss/ir/val/pseudo_labels'
    val_images_folder: '../../../datasets/navigation/ss/ir/val/all'
    augmentation:
        homographic:
            enable_train: false
            enable_val: false
            valid_border_margin: 0
        photometric:
            enable_train: true
            enable_val: false
            random_order: true
            augmentations:
                - CoarseDropout:
                    max_holes: 75
                    max_height: 1
                    max_width: 1
                    fill_value: 0
                    p: 0.5
                - CoarseDropout:
                    max_holes: 10
                    max_height: 2
                    max_width: 2
                    fill_value: 0
                    p: 0.5
                - CoarseDropout:
                    max_holes: 75
                    max_height: 1
                    max_width: 1
                    fill_value: 255
                    p: 0.5
                - CoarseDropout:
                    max_holes: 10
                    max_height: 2
                    max_width: 2
                    fill_value: 255
                    p: 0.5
                - ISONoise:
                    color_shift:
                      - 0.01
                      - 0.05
                    intensity:
                      - 0.1
                      - 0.5
                    p: 1.0
                - GaussNoise:
                    var_limit:
                      - 0.0
                      - 0.1
                    p: 1.0
                - GaussianBlur:
                    blur_limit:
                      - 1
                      - 3
                    p: 1.0
                - MotionBlur:
                    blur_limit:
                      - 3
                      - 5
                    p: 0.75
                - RandomBrightnessContrast:
                    brightness_limit: 0.2
                    contrast_limit: 0.2
                    p: 1.0

    dataset: "ImagesDataset"
    homography_adaptation:
        enable: false
    preprocessing:
        resize: [240, 320]
    val_workers: 16
    train_workers: 16
    truncate: null
    warped_pair:
        enable: true
        params:
            allow_artifacts: true
            max_angle: 1.57
            patch_ratio: 0.85
            perspective: true
            perspective_amplitude_x: 0.2
            perspective_amplitude_y: 0.2
            rotation: true
            scaling: true
            scaling_amplitude: 0.2
            translation: true
        valid_border_margin: 3
logging:
    directory: "../assets/logs"
    level: "DEBUG"
model:
    batch_size: 16
    dense_loss:
        enable: false
        params:
            descriptor_dist: 4
            lambda_d: 800
    detection_threshold: 0.015
    detector_loss:
        enable: true
        loss_type: "softmax"
    eval_batch_size: 8
    lambda_loss: 1
    learning_rate: 0.0001
    name: "SuperPointPretrained"
    pretrained: null
    nms_radius: 4
    remove_borders: 4
    max_num_keypoints: null
    params: {}
    sparse_loss:
        enable: true
        params:
            dist: cos
            lamda_d: 1
            method: 2d
            num_masked_non_matches_per_match: 100
            num_matching_attempts: 1000

precision: medium
pretrained: null
reset_iter: true
save_interval: 2000
seed: 0
tensorboard_interval: 200
train_iter: 200000
validation_interval: 20000
