data:
    dataset: 'ImagesDataset'
    val_labels_folder: '../../../datasets/navigation/pitts250k/images/train/pseudo_labels'
    val_images_folder: '../../../datasets/navigation/pitts250k/images/train/all'
    labels: null
    cache_in_memory: false
    truncate: null
    num_parallel_calls: 10
    validation_size: 1
    preprocessing:
        resize: [240, 320]
    gaussian_label:
        enable: false
    augmentation:
        photometric:
            enable_train: false
            enable_val: false
        homographic:
            enable_train: false
            enable_val: false
            valid_border_margin: 0
    homography_adaptation:
        enable: true
        num: 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                allow_artifacts: true
                patch_ratio: 0.85
    warped_pair:
        enable: false
        valid_border_margin: 0
    
    train_workers: 16
    val_workers: 16

model:
    name: 'SuperPointNet'
    detection_threshold: 0.005
    nms_radius: 4
    max_num_keypoints: 1024
    remove_borders: 4
    nn_thresh: 0.7
    top_k: 1024
    batch_size: 1
    eval_batch_size: 1
    params: {}
    subpixel:
        enable: true

pretrained: '../assets/logs/magicpoint_synth_2024-10-07_10:34:55/checkpoints/SuperPointNet_34000_checkpoint.pth.tar'
skip_existing: false
save_images: true

seed: 0
precision: medium
logging:
  level: DEBUG
  directory: ../assets/logs/generate_pseudo_labels
