data:
    dataset: 'Coco'
    data_path: '../assets/datasets/coco/train2014'
    export_folder: 'train' # train, val
    preprocessing:
        resize: [240, 320] 
        # resize: [480, 640] 
    gaussian_label:
        enable: false # false
        sigma: 1.
    augmentation:
        photometric:
            enable: false
    homography_adaptation:
        enable: true
        num: 100 # 100
        aggregation: 'sum'
        filter_counts: 0
        homographies:
            params:
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2
                perspective_amplitude_x: 0.2
                perspective_amplitude_y: 0.2
                allow_artifacts: true
                patch_ratio: 0.85
    workers: 16

model:
    name: 'SuperPointNet'
    params: {
    }    
    batch_size: 1
    eval_batch_size: 1
    detection_threshold: 0.015 # 0.015
    nms: 4
    nn_thresh: 0.7
    top_k: 600
    subpixel:
        enable: true

pretrained: '../assets/logs/magicpoint_synth_2024-09-27_18:25:15/checkpoints/superPointNet_200000_checkpoint.pth.tar'
skip_existing: false

seed: 0
precision: medium
logging:
  level: DEBUG
  logs_dir: ./assets/logs/generate_pseudo_labels