data:
    dataset: 'ImagesDataset'
    val_images_folder: '../../../Data/coco2014/train/images'
    val_labels_folder: null
    cache_in_memory: false
    truncate: null
    num_parallel_calls: 10
    preprocessing:
        resize: [240, 320]
    gaussian_label:
        enable: false
    augmentation:
        photometric:
            enable_train: false
            enable_val: false
        homographic:
            enable_train: false
            enable_val: false
    homography_adaptation:
        enable: false
    warped_pair:
        enable: false
    
    train_workers: 16
    val_workers: 16

model:
    name: 'SuperPoint'
    pretrained: '../assets/logs/magicpoint_synth_2025-05-04_14:52:55/checkpoints/SuperPoint_199000_checkpoint.pth.tar'
    detection_threshold: 0.015
    nms_radius: 4
    max_num_keypoints: 1024
    remove_borders: 8
    batch_size: 1
    eval_batch_size: 1

skip_existing: false
save_images: true

seed: 0
precision: medium
logging:
  level: DEBUG
  directory: ../assets/logs/generate_pseudo_labels
