data:
    preprocessing:
        resize: [240, 320]

model:
    name: 'SuperPoint'
    pretrained: '../assets/logs/magicpoint_synth_2025-05-02_00:44:14/checkpoints/SuperPoint_190000_checkpoint.pth.tar'
    detection_threshold: 0.015
    nms_radius: 48
    max_num_keypoints: 1024
    remove_borders: 4
    batch_size: 1
    eval_batch_size: 1

save_images: true

seed: 0
precision: medium
logging:
  level: DEBUG
  directory: ../assets/logs/inference
