data:
    dataset: 'HPatchesDataset'
    path: '../../../Data/hpatches/'
    alteration: 'all' # 'all' or 'i' or 'v'
    preprocessing:
        resize: [240, 320]

model:
    name: 'SuperPoint'
    pretrained: '../assets/pretrained/superpoint_v6_from_tf.pth'
    detection_threshold: 0.015
    nms_radius: 4
    max_num_keypoints: 1024
    remove_borders: 8
    top_k: 1024
    batch_size: 1
    eval_batch_size: 1

tracker:
    max_length: 2
    nn_thresh: 0.7

logging:
  level: INFO
  directory: ../assets/logs/evaluation
